/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    ConfirmLogout: typeof import('./components/dialogs/confirm-logout.vue')['default']
    CustomToast: typeof import('./components/CustomToast.vue')['default']
    FormAlert: typeof import('./components/alerts/FormAlert.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    MobileMenu: typeof import('./components/layout/MobileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
