/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[product]': RouteRecordInfo<'/[product]', '/:product', { product: ParamValue<true> }, { product: ParamValue<false> }>,
    '/401': RouteRecordInfo<'/401', '/401', Record<never, never>, Record<never, never>>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/503': RouteRecordInfo<'/503', '/503', Record<never, never>, Record<never, never>>,
    '/auth/[product]': RouteRecordInfo<'/auth/[product]', '/auth/:product', { product: ParamValue<true> }, { product: ParamValue<false> }>,
    '/logout/[[forced]]': RouteRecordInfo<'/logout/[[forced]]', '/logout/:forced?', { forced?: ParamValueZeroOrOne<true> }, { forced?: ParamValueZeroOrOne<false> }>,
  }
}
